### ISSUE TITLE
(wish) Распознавание координаты доски

### ISSUE THREAD

**Issue by kvichans** [IlyaKirillov/GoUniverse#14]
Похоже, что сейчас в чате игры координаты доски распознаются примерно таким рег.выражением 
`\s[ABCDEFGHJKLNOPQRST][1-9][0-9]?\s`
то есть требуются пробелы по сторонам. 
Хорошо бы смягчить условие до, например, такого
`\b[ABCDEFGHJKLNOPQRST][1-9][0-9]?\b`
то есть ожидать начало/конец слова.
Это сделает "живыми" координаты в окружении знаков препинания и в других сложных случаях.

**Comment by IlyaKirillov** [comment]
Распознавание координат работает не регулярными выражениями, поэтому лучше скажите какая конкретно строка неправильно отработала.

**Comment by kvichans** [comment]
Да, нужно было процитировать строку. Но это было под ФФ и мне не удалось ее скопировать - описал проблему в #15.

Сейчас я ту строку точно не помню. Что-то вроде
`Слова ,D6- слова`
