### ISSUE TITLE
Нагрузка на процессор при просмотре живой партии

### ISSUE THREAD

**Issue by kvichans** [IlyaKirillov/GoUniverse#19]
При наблюдении за чужой живой игрой GU заметно нагружает процессор: от 6% до 15%.
Подозреваю, что это так "часы тикают".
Эта неоправданная нагрузка. Хорошо бы от нее избавиться.
Например, разделить на отображение "для игрока" и "для наблюдателя".
Игроку может быть действительно важно **видеть все** (но как?) десятые доли секунд.
А вот наблюдателю они не нужны. Для него вполне достаточно, чтобы часы тикали 2-3 раза в секунду.

**Comment by IlyaKirillov** [comment]
Загрузил просмотр 5 партий одновременно, ни раза выше 4% нагрузка не поднималась.

**Comment by kvichans** [comment]
Провел еще раз тест. Следил за прожорливостью браузера.
- До открытия партии на просмотр - 2-3% и в ФФ и в Хроме.
- При просмотре - 9-11% в ФФ, 4-5% в Хроме.

Значит это наблюдение пригодится при адаптации GU под ФФ.

----
PS Размер шрифтов не gou.coildomain.com поменял, а я сам себе через плагины ФФ.

**Comment by IlyaKirillov** [comment]
У меня на ФФ на разных компах нагрузка не поднимается выше 6% как и на остальных страницах.
