### ISSUE TITLE
Мобильный Хром

### ISSUE THREAD

**Issue by kvichans** [IlyaKirillov/GoUniverse#21]
В версии Хром для Андроид нет расширений. Поэтому воспользовался GU 1.3.1 через http://gou.coildomain.com 
В целом - все работает нормально. Играть еще не пробовал. Наблюдать с планшета 10" очень классно! 

Мелкия неприятность - в списке игр почти нет прокрутки. Свайп вниз не опознается. Скролбар/бегунок не действуют. Точнее мне удалось найти единственный способ - долгий (не двойной!) клик на бегунок делает его темным и отображет верт.скролбар, после этого можно сделать **одну** прокрытку списка. Но вот попасть пальцем в бегунок проблематично.

**Comment by kvichans** [comment]
Еще непрятность - нет раскладки для портретного просмотра. 
Текущая раскладка почти выдерживает, но смотреть на нее непрятно
![img_20161023_152812](https://cloud.githubusercontent.com/assets/7419630/19626248/e437b806-9935-11e6-8ec3-2935dc711620.jpg)

**Comment by IlyaKirillov** [comment]
Разработка мобильного хрома пока и не ведется. А баги с gou,coildomain.com буду нещадно закрывать, предупреждал. Если там что-то работает с планшета - я рад, но не нужно писать баги на чужой сайт с чужим сервером, с не поддерживаемого устройства (я много раз уже писал, что поддерживается пока только Хром и только на PC).
Какой смысл в этом баге, если для планшетов я планирую вообще другой интерфейс делать?
