### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Manslay** [IlyaKirillov/GoUniverse#3]
1. В просмотре партии вместо "Convert to Askii diagram" должно быть Convert to ASCII diagram. И сама диаграмма называться не Ascii Diagram, а ASCII diagram.
2. Export to Gif - может быть, лучше Export to GIF, по аналогии с SGF?
3. Score Estimate - зачем второе слово с заглавной буквы?
4. В Game info (кнопочка i) последний пункт - Game Info - зачем с заглавной буквы?
5. В About copyright 2014-2015. Пора бы на 2016 поменять. А по секции Keyboard Shortcuts отдельный разговор, там тоже очень много опечаток.
6. Settings -> Appearance. Show Target - зачем второе слово с заглавной буквы?
7. Settings -> Loading Settings - "Load unfinished files on the last node" - Явно ошибка перевода, что там имелось в виду по-русски?
8. В информации об игроке UserName -> User name, а дату-время в поле Last on неплохо бы привести к читаемому виду.

Вроде пока всё из бросающегося в глаза.

P.S. Очень круто всё сделано!

**Comment by IlyaKirillov** [comment]
Да, с английским у меня печально все :)

**Comment by IlyaKirillov** [comment]
Fixed.

8. Пункт сделал так: 
Last on:	4 hours ago (03.08.2016, 20:23:09)
