### ISSUE TITLE
увеличение игрового поля

### ISSUE THREAD

**Issue by al-shch** [IlyaKirillov/GoUniverse#35]
Ввиду того, что в большинстве своем сейчас экраны 12:9 или иные широкоформатные, игровое поле относительно невелико, особенно, если играть на ноутбуке с небольшой диагональю.
есть предложение увеличить размер игрового поля, путем перемещения части меню вправо и увеличением игрового поля за счет высвободившегося места.
![img3-1](https://cloud.githubusercontent.com/assets/27990851/25376173/e1a5b44a-29d5-11e7-8f43-aa0e76f3eb28.png)
![img3-2](https://cloud.githubusercontent.com/assets/27990851/25376180/e4c4d6f6-29d5-11e7-9762-98b5f5f96d55.png)

на картинке 3-1 показано как есть сейчас и какие изменения предлагается внести.
На картинке 3-2 показано как могло бы выглядеть увеличенное игровое поле.

**Comment by IlyaKirillov** [comment]
В браузере можно просто нажать F11 (полноэкранный режим, потом добавлю кнопку, чтобы прямо из клиента это делать), совсем отказываться от верхней полоски ради 20 пикселей для чуть большего размера доски я не вижу смысла.
