### ISSUE TITLE
writing/editing text is too small

### ISSUE THREAD

**Issue by scottdraves** [IlyaKirillov/GoUniverse#54]
perhaps this is because i have a retina screen?
but this is on a mac with chrome Version 59.0.3071.115 (Official Build) (64-bit)
![screen shot 2017-08-01 at 11 23 54 am](https://user-images.githubusercontent.com/963093/28833021-24336028-76ac-11e7-91c3-a4f68d46bd0e.png)

same for when i am playing a game.

**Comment by IlyaKirillov** [comment]
It will be fixed in the next 1.5.7 version

**Comment by scottdraves** [comment]
thank you great to hear it, looking forward to seeing it :)
