### ISSUE TITLE
Не могу открыть свою же приватную игру

### ISSUE THREAD

**Issue by anatoliin** [IlyaKirillov/GoUniverse#57]
Собственно ничего не дает с ней сделать из списка. Все пункты в попап меню задизейблены.

**Comment by IlyaKirillov** [comment]
Это была обычная приватная игра, разбор или демонстрация?

**Comment by anatoliin** [comment]
anatoliin vs rus172 от 25.08.2017

**Comment by IlyaKirillov** [comment]
Версия 1.5.7. Добавил возможность загружать приватные партии в комнату. Просмотр и скачивание сделать нельзя, т.к. запрещено с сайта грузить приватные партии.
