### ISSUE TITLE
Crash when observing game and player resigns

### ISSUE THREAD

**Issue by killerducky** [IlyaKirillov/GoUniverse#6]
I started observing a game, and did right click -> view info one of the players. When a player resigned the game, the client crashed. Reproduced this a few times.

**Comment by IlyaKirillov** [comment]
If by "crash" you mean Logout, then I had found this one too.  It often happens when you are checking some info and this player start/end a game.  In real it is not GoUniverse problem, it is server problem. Server send command "logout" to client in such situation.

**Comment by KirillovIlya** [comment]
https://groups.google.com/forum/#!topic/kgs-client-coding/WPzk4bTsu90

Fixed in new version of Translator jsonClient-2016-08-26T02_21Z.war

**Comment by IlyaKirillov** [comment]
https://groups.google.com/forum/#!topic/kgs-client-coding/WPzk4bTsu90

Fixed in new version of Translator jsonClient-2016-08-26T02_21Z.war
