### ISSUE TITLE
Need setup instruction

### ISSUE THREAD

**Issue by kvichans** [IlyaKirillov/GoUniverse#61]
Можно ли в README.md  добавить шаги, которые нужны, чтобы начать пользоваться GoUniverse?

Может быть кроме README.md, где-то уже есть более подробная инструкция. Тогда нужна ссылка на нее.

**Comment by IlyaKirillov** [comment]
Вы можете свободно пользоваться магазином Chrome,там никаких инструкций не требуется. Пока ни в каком другом виде данное приложение не поставляется.

**Comment by kvichans** [comment]
Для FF не будет версии?
