### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Pestr** [IlyaKirillov/GoUniverse#65]
The browser shows errors 
"Failed to load resource: net::ERR_EMPTY_RESPONSE"
and cannot load sound files:
webgoboard.com/Sound/Capture1.mp3
webgoboard.com/Sound/Capture3.mp3
webgoboard.com/Sound/Capture5.mp3
webgoboard.com/Sound/CaptureN.mp3
webgoboard.com/Sound/NewMessage.mp3
etc.

**Comment by IlyaKirillov** [comment]
1.5.10 fixed

**Comment by Pestr** [comment]
Now is no errors, but no sound too.

**Comment by IlyaKirillov** [comment]
You may have turned off the sound in the settings
