### ISSUE TITLE
Cannot connect post Server Update

### ISSUE THREAD

**Issue by Lecale** [IlyaKirillov/GoUniverse#66]
Sometime in September 2019, the Server was updated. Since then GoUniverse cannot connect. ShinKGS was initially unable to connect, but on 20th Sept it can connect.
Do you know what the issue is? Can it be corrected?

**Comment by IlyaKirillov** [comment]
Hello. 

As I understand it, the KGS server was updated and moved, after that access was closed through the GoUniverse. I've tried to contact the KGS administrators, but so far this has not brought down anything. Still don't know what I need to do to fix this.

**Comment by c0nnex** [comment]
a) change the url to https://www.gokgs.com/json-cors/access (KGS/client.js, two locations)
b) There is apparently a CORS issue.
The KGS Api Server does not send a "Access-Control-Allow-Origin" Header for the request, thus modern browsers rejecting to call it.
It does send that header for official ShinKGS Server, so apparently KGS locked you out. 
You can start eg. chrome with disabled cors:
``` ./chrome.exe --user-data-dir="G:/Chrome dev session" --disable-web-security```
Then GoUniverse will work (if you changed the url)

(You could easily find that out by using the Chrome-Debugger. Took me 15 mins to nail down and confirm the issue ...)

**Comment by IlyaKirillov** [comment]
Thank you.

This is a good solution for an particular user, but not for the entire application.

**Comment by Hendeca** [comment]
@c0nnex I have tried your solution but found that after altering the extension code, Google sees the extension as corrupt and won't allow it to be enabled. I also tried just downloading the source code and running it, but it seems that the file paths are not working when I try doing it this way. I tried both running it via MAMP (I am on a mac) and by navigating directly to the file. Any ideas?

**Comment by IlyaKirillov** [comment]
> a) change the url to https://www.gokgs.com/json-cors/access (KGS/client.js, two locations)
> b) There is apparently a CORS issue.
> The KGS Api Server does not send a "Access-Control-Allow-Origin" Header for the preflight OPTIONS request, thus modern browsers rejecting to call the real service.
> It does send that header for official ShinKGS Server, so apparently KGS locked you out.
> You can start eg. chrome with disabled cors:
> ` ./chrome.exe --user-data-dir="G:/Chrome dev session" --disable-web-security`
> Then GoUniverse will work (if you changed the url)
> 
> (You could easily find that out by using the Chrome-Debugger. Took me 15 mins to nail down and confirm the issue ...)


I tried this several times, it doesn’t work for me

**Comment by IlyaKirillov** [comment]
fixed

**Comment by IlyaKirillov** [comment]
fixed
