### ISSUE TITLE
"EPlayersListRecord is not defined" after censoring a player

### ISSUE THREAD

**Issue by killerducky** [IlyaKirillov/GoUniverse#7]
I right-clicked a name in game chat, and censored a user. Then when I scroll the list of players it goes blank, and I see the following error in console:

InGamePlayersList.js:292 Uncaught ReferenceError: EPlayersListRecord is not defined
CKGSInGamePlayersListRecord.Draw @ InGamePlayersList.js:292
CListBase.Draw_Record @ ListBase.js:75
CListView.private_Draw @ ListView.js:651
CListView.private_UpdateMainContext @ ListView.js:569
CListView.private_OnDragVerScroll @ ListView.js:283
Drag @ Common.js:388

Also when right-clicking on a player's name in game chat I get the following error in console:
index.html:1 Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by IlyaKirillov** [comment]
I can't repeat that. Did you have used chrome-extension or foreigh site?

**Comment by IlyaKirillov** [comment]
fixed https://github.com/IlyaKirillov/GoUniverse/commit/dad54a48ad6f8848d8eba7706517139c4fb04ca4

**Comment by IlyaKirillov** [comment]
1.3.0 version fixed
